artifact_uri: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/307928483513336108/8b201fcf5f714da4a41ec13a2677a981/artifacts
end_time: null
entry_point_name: ''
experiment_id: '307928483513336108'
lifecycle_stage: active
run_id: 8b201fcf5f714da4a41ec13a2677a981
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-Red-Single_0d606_00000
run_uuid: 8b201fcf5f714da4a41ec13a2677a981
source_name: ''
source_type: 4
source_version: ''
start_time: 1694363300406
status: 1
tags: []
user_id: unknown
