artifact_location: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/307928483513336108
creation_time: 1694356195969
experiment_id: '307928483513336108'
last_update_time: 1694356195969
lifecycle_stage: active
name: foo
