artifact_location: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/0
creation_time: 1694356195956
experiment_id: '0'
last_update_time: 1694356195956
lifecycle_stage: active
name: Default
