artifact_location: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/524617645511749058
creation_time: 1694365211492
experiment_id: '524617645511749058'
last_update_time: 1694365211492
lifecycle_stage: active
name: pickup_0.01
