artifact_uri: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/922015493486025619/15bb39d9f4634e82ab24168d66e43ea0/artifacts
end_time: null
entry_point_name: ''
experiment_id: '922015493486025619'
lifecycle_stage: active
run_id: 15bb39d9f4634e82ab24168d66e43ea0
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-Red-Single_2558d_00000
run_uuid: 15bb39d9f4634e82ab24168d66e43ea0
source_name: ''
source_type: 4
source_version: ''
start_time: 1694368494756
status: 1
tags: []
user_id: unknown
