artifact_uri: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/307928483513336108/3b7005df5cc746609480f17fbbb994f6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '307928483513336108'
lifecycle_stage: active
run_id: 3b7005df5cc746609480f17fbbb994f6
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-Red-Single_60c49_00000
run_uuid: 3b7005df5cc746609480f17fbbb994f6
source_name: ''
source_type: 4
source_version: ''
start_time: 1694362152196
status: 1
tags: []
user_id: unknown
