artifact_uri: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/307928483513336108/3ee14a4e83b2417fac08d177e4d2b669/artifacts
end_time: null
entry_point_name: ''
experiment_id: '307928483513336108'
lifecycle_stage: active
run_id: 3ee14a4e83b2417fac08d177e4d2b669
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-Red-Single_b7eea_00000
run_uuid: 3ee14a4e83b2417fac08d177e4d2b669
source_name: ''
source_type: 4
source_version: ''
start_time: 1694362728241
status: 1
tags: []
user_id: unknown
