artifact_location: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/922015493486025619
creation_time: 1694365748727
experiment_id: '922015493486025619'
last_update_time: 1694365748727
lifecycle_stage: active
name: pickup_0.005
