artifact_uri: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/307928483513336108/04566ddfeaf24520866796347e63522c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '307928483513336108'
lifecycle_stage: active
run_id: 04566ddfeaf24520866796347e63522c
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-Red-Single_a7088_00000
run_uuid: 04566ddfeaf24520866796347e63522c
source_name: ''
source_type: 4
source_version: ''
start_time: 1694361411003
status: 1
tags: []
user_id: unknown
