artifact_uri: /Users/brian.hone/str_code/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-bthcode/submission/mlflow/524617645511749058/0fc8da1652214ed7946aa69150ad31bb/artifacts
end_time: null
entry_point_name: ''
experiment_id: '524617645511749058'
lifecycle_stage: active
run_id: 0fc8da1652214ed7946aa69150ad31bb
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-Red-Single_80fdd_00000
run_uuid: 0fc8da1652214ed7946aa69150ad31bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1694365212350
status: 1
tags: []
user_id: unknown
